// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrations need a direct (non-pooled) connection. The app's runtime
  // PrismaClient uses DATABASE_URL (pooled) instead — see src/lib/db.ts.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
